services:
  - type: web
    name: tesseract-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y curl tesseract-ocr tesseract-ocr-eng tesseract-ocr-hrv
      curl -Ls https://astral.sh/uv/install.sh | bash
      export PATH="$HOME/.cargo/bin:$PATH"
      uv pip install -r requirements.txt
    startCommand: python app.py
