services:
  - type: web
    name: tesseract-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-hrv libtesseract-dev
      pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT app:app
